--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: demo
    name: web
  name: web1
spec: 
  containers: 
    - image: redis
      name: redis
      ports: 
        - containerPort: 6379
          name: redis
          protocol: TCP
    - image: brunoterkaly/py-red
      name: python
      env: 
        - name: REDIS_HOST
          value: localhost
      livenessProbe:
        httpGet:
          path:  /healthzdb
          port: 5000
        initialDelaySeconds:  30
        timeoutSeconds: 3
      ports: 
        - containerPort: 5000
          name: http
          protocol: TCP

