# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  projectName: py-red
  buildDir: Build
  imageName: $(projectName):$(build.buildId)
  registryName: azureregistrykubernetes
  registryServerName: $(registryName).azurecr.io

  dockerId: brunoterkaly
  azureResourceGroup: rg-my-aks-cluster
  kubernetesCluster: my-aks-cluster
  azureContainerRegistry: azureregistrykubernetes.azurecr.io

trigger:
  branches:
    include:
    - master
    - features/*
  paths:
    include:
    - k8s-multi-container

steps:

- bash: docker build -f $(system.defaultWorkingDirectory)/$(buildDir)/Dockerfile -t $(registryServerName)/$(imageName) -t $(registryServerName)/$(imageName):latest $(system.defaultWorkingDirectory)/$(buildDir)

- bash: 
   echo "Default Working Directory"
- bash: 
   echo $(system.defaultWorkingDirectory)
- bash: 
   ls -latr $(system.defaultWorkingDirectory)

- bash: 
   echo "Project Name"
- bash: 
    echo $(projectName)

- bash: echo $(registryServerName)

- bash: echo $(imageName)

- bash: docker build -f $(system.defaultWorkingDirectory)/$(projectName)/Dockerfile -t $(registryServerName)/$(imageName):$(build.buildId) -t $(registryServerName)/$(imageName):latest $(system.defaultWorkingDirectory)/$(projectName)



  # displayName: 'docker build'

    # Login to Docker

#    docker login -u $(dockerId) -p $(pswd)
#    cd Build
#    docker build -f Dockerfile -t $(dockerId)/$(imageName) .
#    docker push $(dockerId)/$(imageName)

#- task: Kubernetes@1
#  displayName: kubectl apply

# steps:
# - task: Kubernetes@1
#   displayName: kubectl apply
#   inputs:
#     connectionType: Azure Resource Manager
#     azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
#     azureResourceGroup: $(azureResourceGroup)
#     kubernetesCluster: $(kubernetesCluster)

#    command: apply
#    arguments: -f Deploy/web-svc-1.yml

#  inputs:
#    connectionType: Kubernetes Service Connection
#    kubernetesServiceEndpoint: connection-kubernetes
#    containerregistrytype: Container Registry
#    dockerRegistryEndpoint: connection-docker
#    command: login

#    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
#    azureResourceGroup: $(azureResourceGroup)
#    kubernetesCluster: $(kubernetesCluster)
#    command: apply
#    arguments: -f Deploy/web-svc-1.yml
