# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'py-red:$(build.buildId)'
  dockerId: brunoterkaly
  azureResourceGroup: rg-my-aks-cluster
  kubernetesCluster: my-aks-cluster
  azureSubscriptionEndpoint: Contoso
  azureContainerRegistry: contoso.azurecr.io
  azureResourceGroup: Contoso
  kubernetesCluster: Contoso


steps:

- script: |
  
    # Login to Docker
    
    docker login -u $(dockerId) -p $(pswd)
    
    cd Build
    docker build -f Dockerfile -t $(dockerId)/$(imageName) . 
    
    docker push $(dockerId)/$(imageName)

- task: Kubernetes@1
  displayName: kubectl apply


# steps:
# - task: Kubernetes@1
#   displayName: kubectl apply
#   inputs:
#     connectionType: Azure Resource Manager
#     azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
#     azureResourceGroup: $(azureResourceGroup)
#     kubernetesCluster: $(kubernetesCluster)

#    command: apply
#    arguments: -f Deploy/web-svc-1.yml

#  inputs:
#    connectionType: Kubernetes Service Connection
#    kubernetesServiceEndpoint: connection-kubernetes
#    containerregistrytype: Container Registry
#    dockerRegistryEndpoint: connection-docker
#    command: login    

#    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
#    azureResourceGroup: $(azureResourceGroup)
#    kubernetesCluster: $(kubernetesCluster)
#    command: apply
#    arguments: -f Deploy/web-svc-1.yml

