# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
# for web-pod-1.yml
metadata:
  labels:
    app: demo
    name: web
  name: web1
containers:
  image1: redis:latest
  name1: redis
  containerPort1: 6379
  image2: brunoterkaly/py-red
  name2: python
  env:
    name: REDIS_HOST
    value: localhost
    containerPort: 5000

# for web-svc-1.yml
webservice:
  type: LoadBalancer
  port: 80
  targetPort: 5000

# for db-pod-1.yml
mysqlpod:
  name: mysql
  label_name: mysql
  label_app: demo
  container_name: mysql
  container_image: mysql:5.7
  container_port: 3306
  env_name: "MYSQL_ROOT_PASSWORD"
  env_value: "password"

# for db-svc-1.yml
mysqlsvc:
  name: mysql
  label_name: mysql
  label_app: demo
  port_name: mysql
  port_port: 3306
  port_targetport: 3306
  selector_name: mysql
  selector_app: demo
