apiVersion: "v1"
kind: Pod
metadata:
  name: {{ .Values.mysqlpod.name }}
  labels:
    name: {{ .Values.mysqlpod.label_name }}
    app: {{ .Values.mysqlpod.label_app }}
spec:
  containers:
    - name: {{ .Values.mysqlpod.container_name }}
      image: {{ .Values.mysqlpod.container_image }}
      ports:
        - containerPort: {{ .Values.mysqlpod.container_port }}
          protocol: TCP
      env:
        -
          name: {{ .Values.mysqlpod.env_name }}
          value: {{ .Values.mysqlpod.env_value }}
