apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: {{ .Values.metadata.labels.app }}
    name: {{ .Values.metadata.labels.name }}
spec:
  selector:
    name: {{ .Values.metadata.labels.name }}
  type: {{ .Values.webservice.type }}
  ports:
   - port: {{ .Values.webservice.port }}
     name: http
     targetPort: {{ .Values.webservice.targetPort }}
     protocol: TCP
